get:
  summary: List all available deployments
  description: |-
    List or search all `Deployment` resources available from this server endpoint.
  tags:
    - Deployments
  parameters:
    - $ref: ../parameters/idList.yaml
    - $ref: ../parameters/bbox.yaml
    - $ref: ../parameters/datetime.yaml
    - $ref: ../parameters/geom.yaml
    - $ref: ../parameters/keyword.yaml
    - $ref: ../parameters/parentIdList.yaml
    - $ref: ../parameters/systemIdList.yaml
    - $ref: ../parameters/foiIdList.yaml
    - $ref: ../parameters/obsPropIdList.yaml
    - $ref: ../parameters/controlPropIdList.yaml
    #- $ref: '#/components/parameters/select'
    - $ref: ../parameters/limit.yaml
  responses:
    '200':
      $ref: ../responses/deploymentCollection.yaml
    '400':
      $ref: ../responses/StandardResponses.yaml#/400
    '401':
      $ref: ../responses/StandardResponses.yaml#/401
    '403':
      $ref: ../responses/StandardResponses.yaml#/403
    '404':
      $ref: ../responses/StandardResponses.yaml#/404
    '5XX':
      $ref: ../responses/StandardResponses.yaml#/5XX

post:
  summary: Create a deployment
  description: |-
    Add a new top-level `Deployment` resource.
  tags:
    - Deployments
  requestBody:
    $ref: ../requests/deployment.yaml
  responses:
    '201':
      $ref: ../responses/StandardResponses.yaml#/201
    '400':
      $ref: ../responses/StandardResponses.yaml#/400
    '401':
      $ref: ../responses/StandardResponses.yaml#/401
    '403':
      $ref: ../responses/StandardResponses.yaml#/403
    '404':
      $ref: ../responses/StandardResponses.yaml#/404
    '5XX':
      $ref: ../responses/StandardResponses.yaml#/5XX