get:
  summary: List subdeployments
  description: |-
    List or search all `Deployment` resources that are part of a specific parent deployment.

    Note that individual members can also be retrieved by ID directly at the canonical `Deployment` resources endpoint.
  tags:
    - Deployments
  parameters:
    - $ref: ../parameters/deploymentId.yaml
    - $ref: ../parameters/idList.yaml
    - $ref: ../parameters/bbox.yaml
    - $ref: ../parameters/datetime.yaml
    - $ref: ../parameters/geom.yaml
    - $ref: ../parameters/keyword.yaml
    - $ref: ../parameters/parentIdList.yaml
    - $ref: ../parameters/systemIdList.yaml
    - $ref: ../parameters/foiIdList.yaml
    - $ref: ../parameters/obsPropIdList.yaml
    - $ref: ../parameters/controlPropIdList.yaml
    - $ref: ../parameters/recursive.yaml
      description: If true, instructs the server to include nested subdeployments, recursively.
    #- $ref: '#/components/parameters/select'
    - $ref: ../parameters/limit.yaml
  responses:
    '200':
      $ref: ../responses/deploymentCollection.yaml
    '400':
      $ref: ../responses/StandardResponses.yaml#/400
    '401':
      $ref: ../responses/StandardResponses.yaml#/401
    '403':
      $ref: ../responses/StandardResponses.yaml#/403
    '404':
      $ref: ../responses/StandardResponses.yaml#/404
    '5XX':
      $ref: ../responses/StandardResponses.yaml#/5XX
      
post:
  summary: Add a subdeployment
  tags:
    - Deployments
  parameters:
    - $ref: ../parameters/deploymentId.yaml
  requestBody:
    $ref: ../requests/deployment.yaml
  responses:
    '201':
      $ref: ../responses/StandardResponses.yaml#/201
    '400':
      $ref: ../responses/StandardResponses.yaml#/400
    '401':
      $ref: ../responses/StandardResponses.yaml#/401
    '403':
      $ref: ../responses/StandardResponses.yaml#/403
    '404':
      $ref: ../responses/StandardResponses.yaml#/404
    '5XX':
      $ref: ../responses/StandardResponses.yaml#/5XX